# docker-compose -f "Docker.Compose.yaml" up -d --build 
name: project-csi
services:
  #
  # ฐานข้อมูล: MySQL
  # การเชื่อมต่อ: 44102
  #
  DbMySQL:
    container_name: DbMySQL
    image: mysql:lts
    restart: always
    hostname: DbMySQL
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
    ports:
      - "51100:3306"
    volumes:
      - "./backend/data/sql:/var/lib/mysql"
    networks:
      - DbNetwork

  #
  # ฐานข้อมูล: PhpMyAdmin
  # การเชื่อมต่อ: 44001
  #
  DbPhpMyAdmin:
    container_name: DbPhpMyAdmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "50001:80"
    environment:
      - PMA_HOST=DbMySQL
      - PMA_PORT=3306
    networks:
      - DbNetwork
    depends_on:
      - DbMySQL

networks:
  DbNetwork:
    name: DbNetwork